# FROM apache/airflow:latest

# USER root
# RUN apt-get update && \
#     apt-get -y install && \
#     apt-get clean

# USER airflow

FROM apache/airflow:latest 

# Install system dependencies as root
USER root
RUN apt-get update && apt-get install -y gcc libpq-dev && apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch to airflow user to install Python packages
USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
